### ISSUE TITLE
findPrevious 与 remove 有不足

### ISSUE THREAD

**Issue by xushiqing** [NLRX-WJC/Data-Structure-by-JavaScript#1]
findPrevivous 查找head的值时会报错，由此remove删除head也会出错

**Comment by NLRX-WJC** [comment]
具体报什么错或者什么情况下报错，可以贴一段代码上来我看一下

**Comment by NLRX-WJC** [comment]
我刚测试了一下确实有点问题，非常感谢帮我指出，我抽时间修复一下，再次感谢

**Comment by NLRX-WJC** [comment]
已修复，感谢指正

**Comment by xushiqing** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"难凉热血"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月11日(星期三) 下午4:58
收件人:&nbsp;"NLRX-WJC/Data-Structure-by-JavaScript"<Data-Structure-by-JavaScript@noreply.github.com&gt;;
抄送:&nbsp;"strayer"<1126579117@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [NLRX-WJC/Data-Structure-by-JavaScript] findPrevious 与 remove 有不足 (#1)




已修复，感谢指正

**Comment by xushiqing** [comment]
我也是学习使用了你的代码，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"难凉热血"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月11日(星期三) 下午4:58
收件人:&nbsp;"NLRX-WJC/Data-Structure-by-JavaScript"<Data-Structure-by-JavaScript@noreply.github.com&gt;;
抄送:&nbsp;"strayer"<1126579117@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [NLRX-WJC/Data-Structure-by-JavaScript] findPrevious 与 remove 有不足 (#1)




已修复，感谢指正
